"""
Neighbor-Joining tree builder module.

This module provides the NeighborJoining class, responsible for building
a phylogenetic tree from a distance matrix using the Neighbor-Joining
algorithm.

The class receives the element names and the full square distance matrix
loaded by MatrixLoader, converts them to the format expected by BioPython,
and then uses BioPython's DistanceTreeConstructor to build the tree.
"""

# Libraries 
from typing import List

from Bio.Phylo.BaseTree import Tree
from Bio.Phylo.TreeConstruction import DistanceMatrix, DistanceTreeConstructor

try:
    from damicore_tree_builder.matrix_loader import MatrixLoader
except ModuleNotFoundError:
    from matrix_loader import MatrixLoader

# Neighbor-Joining tree builder class
class NeighborJoining:
    """
    Builds a tree using the Neighbor-Joining algorithm.

    The NeighborJoining class receives a list of element names and a full
    square distance matrix. It converts the matrix to BioPython's
    DistanceMatrix format and applies the Neighbor-Joining algorithm.

    BioPython expects the distance matrix in lower triangular format,
    including the diagonal. For example, a full matrix like:

        [
            [0.0, 5.0, 9.0],
            [5.0, 0.0, 10.0],
            [9.0, 10.0, 0.0],
        ]

    must be converted to:

        [
            [0.0],
            [5.0, 0.0],
            [9.0, 10.0, 0.0],
        ]
    """

    # Builder initialization
    def __init__(self, names: List[str], matrix: List[List[float]]) -> None:
        """
        Initializes the NeighborJoining tree builder.

        Args:
            names: List of element names.
            matrix: Full square distance matrix.
        """
        self.names = names
        self.matrix = matrix

    
    # Auxiliary functions
    def _validate_input(self) -> None:
        """
        Validates whether the names and matrix are compatible.
        """
        if not self.names:
            raise ValueError("The names list cannot be empty.")

        if not self.matrix:
            raise ValueError("The distance matrix cannot be empty.")

        if len(self.names) != len(self.matrix):
            raise ValueError(
                "The number of names must match the number of matrix rows."
            )

        for row in self.matrix:
            if len(row) != len(self.names):
                raise ValueError(
                    "The distance matrix must be square and match the number of names."
                )

        if len(self.names) < 3:
            raise ValueError(
                "Neighbor-Joining requires at least 3 elements to build a tree."
            )

    def _to_biopython_distance_matrix(self) -> DistanceMatrix:
        """
        Converts a full square matrix to BioPython's DistanceMatrix format.

        Returns:
            A BioPython DistanceMatrix object.
        """
        lower_triangle_matrix = []

        for row_index in range(len(self.matrix)):
            lower_triangle_row = []

            for column_index in range(row_index + 1):
                value = float(self.matrix[row_index][column_index])
                lower_triangle_row.append(value)

            lower_triangle_matrix.append(lower_triangle_row)

        return DistanceMatrix(names=self.names, matrix=lower_triangle_matrix)

    
    # Main function
    def build_tree(self) -> Tree:
        """
        Builds a Neighbor-Joining tree from the distance matrix.

        Returns:
            A BioPython Tree object generated by the Neighbor-Joining algorithm.

        Raises:
            ValueError: If the input names and matrix are inconsistent.
        """
        self._validate_input()

        distance_matrix = self._to_biopython_distance_matrix()

        constructor = DistanceTreeConstructor()
        tree = constructor.nj(distance_matrix)

        return tree
    
if __name__ == "__main__":
    loader = MatrixLoader()

    try:
        names, matrix = loader.load()

        builder = NeighborJoining(names, matrix)
        tree = builder.build_tree()

        print("Neighbor-Joining tree built successfully.")
        print(f"Number of terminals: {len(tree.get_terminals())}")
        print(f"Terminal names: {[terminal.name for terminal in tree.get_terminals()]}")
        print("\nTree:")
        print(tree)

    except (FileNotFoundError, ValueError) as error:
        print(f"Error while building Neighbor-Joining tree: {error}")