"""
Newick tree writer module.

This module provides the NewickWriter class, responsible for saving a
phylogenetic tree in Newick format.

The class receives a tree object generated by the Neighbor-Joining algorithm
and writes it to an output file using BioPython's Phylo module.
"""

# Libraries
from pathlib import Path

from Bio import Phylo
from Bio.Phylo.BaseTree import Tree

# Newick tree writer class
class NewickWriter:
    """
    Writes a phylogenetic tree to a Newick file.

    The NewickWriter class is responsible only for output persistence. It does
    not build the tree and does not create the final execution contract. Its
    only responsibility is to receive a BioPython Tree object and save it in
    Newick format.
    """
